#!/bin/bash

DEST=/run/media/savage/b403a3d9-cc2c-4e8b-9aa1-88b4ee0d41e8/savage/torrents/anime
BLURAY_DEST=~/run/media/savage/b403a3d9-cc2c-4e8b-9aa1-88b4ee0d41e8/savage/torrents/anime/Blu-rays

move () {
	if [ -d "$2"/"$1" ]
	then
		echo "The [$1] directory already exists..."
		echo "Moving the file [$3] to [$1] directory..."
		rsync -avh --progress "$3" "$2"/"$1"
		rm -r "$3"
		#mv "$3" "$2"/"$1"
	else
		echo "Making a [$1] directory..."
		mkdir "$2"/"$1"
		echo "Moving the file [$3] to [$1] directory..."
		rsync -avh --progress "$3" "$2"/"$1"
		rm -r "$3"
		#mv "$3" "$2"/"$1"
	fi
}

cd $DEST
for file in *
do
	part1=$(echo "$file" | cut -b 1-4)
	case $part1 in
		"[Hor")
			part2=${file/\[HorribleSubs\]\ /}
			if [[ "$part2" == *"720"* ]];
			then
				filename=${part2/\ \-\ [0-9][0-9]\ \[720p\].mkv/}
				move "$filename" "$DEST" "$file"
			else	
				filename=${part2/\ \-\ [0-9][0-9]\ \[1080p\].mkv/}
				move "$filename" "$DEST" "$file"
			fi
			;;
		"[FFF")
			part2=${file/\[FFF\]\ /}
			filename=${part2/\ \-\ Vol.0[0-9]\ \[BD\]\[1080p\-FLAC\]/}
			move "$filename" "$BLURAY_DEST" "$file"
			;;
		"[Blu")
			part2=${file/\[BlurayDesuYo\]\ /}
			filename=${part2/\ \-\ Vol.\ [0-9]\ \(BD\ 1920x1080\ 10bit\ FLAC\)/}
			move "$filename" "$BLURAY_DEST" "$file"
			;;
		"[Sal")
			part2=${file/\[SallySubs\]\ /}
			filename=${part2/\ \-\ Vol.0[0-9]\ \[BD\ 1080p\ FLAC\]/}
			move "$filename" "$BLURAY_DEST" "$file"
			;;
		*)
	esac
done
